version: "1.0"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  
  frontend:
    build:
      context: ./react/emission-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
