version: "1.0"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${FASTAPI_PORT}:8000
  
  frontend:
    build:
      context: ./react/emission-app
      args:
        REACT_APP_FASTAPI_PORT: ${FASTAPI_PORT}
        REACT_APP_PORT: ${REACT_PORT}
      dockerfile: Dockerfile
    ports:
      - ${REACT_PORT}:${REACT_PORT}
